apiVersion: v1
kind: Service
metadata:
  name: iris-model-app
  namespace: fraud
spec:
  selector:
    app: iris-model-app
  ports:
  - protocol: TCP
    port: 1957
    targetPort: 1957
  type: NodePort